version: '3'

services:

  jm_app:
    container_name: berniris_app
    restart: always
    build: ./dash_app
    ports:
      - "5020:5020"
    command: gunicorn -w 1 -b :5020 john:server


  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - jm_app
